#!/usr/bin/env python
import os, sys, traceback

from disco.error import DataError
from disco.events import DataUnavailable, TaskFailed
from disco.worker.classic.worker import Worker
from disco.util import MessageWriter

if __name__ == '__main__':
    try:
        sys.stdout = MessageWriter()
        Worker()
    except (DataError, EnvironmentError, MemoryError), e:
        # check the number of open file descriptors (under proc), warn if close to max
        # http://stackoverflow.com/questions/899038/getting-the-highest-allocated-file-descriptor
        # also check for other known reasons for error, such as if disk is full
        DataUnavailable(traceback.format_exc()).send()
        raise
    except Exception, e:
        TaskFailed(MessageWriter.force_utf8(traceback.format_exc())).send()
        raise
